#############################################################################
# Generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#  Jan 25, 2019 11:35:07 AM EST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Segoe UI} -size 24 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font9
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top37
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m50" -background {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 681x540+650+150
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1061
    wm minsize $top 176 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Device Information"
    vTcl:DefineAlias "$top" "TopLevel" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure Frame -background #d9d9d9
    ttk::style configure Frame -foreground #000000
    ttk::style configure Frame -font TkDefaultFont
    frame $top.fra42 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 75 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.fra42" "DeviceInfo" vTcl:WidgetProc "TopLevel" 1
    set site_3_0 $top.fra42
    label $site_3_0.lab43 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Context 
    vTcl:DefineAlias "$site_3_0.lab43" "IIO_Context" vTcl:WidgetProc "TopLevel" 1
    vTcl:copy_lock $site_3_0.lab43
    labelframe $site_3_0.lab44 \
        -font TkDefaultFont -foreground black -text Devices \
        -background {#d9d9d9} -height 165 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 320 
    vTcl:DefineAlias "$site_3_0.lab44" "DeviceFrame" vTcl:WidgetProc "TopLevel" 1
    set site_4_0 $site_3_0.lab44
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_4_0.scr54 \
        -background {#d9d9d9} -height 75 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_4_0.scr54" "Devices" vTcl:WidgetProc "TopLevel" 1

    $site_4_0.scr54.01 configure -background white \
        -disabledforeground #a3a3a3 \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -selectmode single \
        -width 10
    vTcl:copy_lock $site_4_0.scr54
    place $site_4_0.scr54 \
        -in $site_4_0 -x 0 -y 0 -rely 0.185 -width 0 -relwidth 1 -height 0 \
        -relheight 0.8 -anchor nw -bordermode ignore 
    vTcl:copy_lock $site_3_0.lab44
    labelframe $site_3_0.lab45 \
        -font TkDefaultFont -foreground black -text Attributes \
        -background {#d9d9d9} -height 165 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 320 
    vTcl:DefineAlias "$site_3_0.lab45" "AttrFrame" vTcl:WidgetProc "TopLevel" 1
    set site_4_0 $site_3_0.lab45
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_4_0.scr54 \
        -background {#d9d9d9} -height 75 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_4_0.scr54" "Attrs" vTcl:WidgetProc "TopLevel" 1

    $site_4_0.scr54.01 configure -background white \
        -disabledforeground #a3a3a3 \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -selectmode single \
        -width 10
    vTcl:copy_lock $site_4_0.scr54
    place $site_4_0.scr54 \
        -in $site_4_0 -x 0 -y 0 -rely 0.185 -width 0 -relwidth 1 -height 0 \
        -relheight 0.8 -anchor nw -bordermode ignore 
    labelframe $site_3_0.lab46 \
        -font TkDefaultFont -foreground black -text {Debug Attributes} \
        -background {#d9d9d9} -height 165 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 320 
    vTcl:DefineAlias "$site_3_0.lab46" "DebugAttrsFrame" vTcl:WidgetProc "TopLevel" 1
    set site_4_0 $site_3_0.lab46
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_4_0.scr54 \
        -background {#d9d9d9} -height 75 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_4_0.scr54" "DebugAttrs" vTcl:WidgetProc "TopLevel" 1

    $site_4_0.scr54.01 configure -background white \
        -disabledforeground #a3a3a3 \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -selectmode single \
        -width 10
    vTcl:copy_lock $site_4_0.scr54
    place $site_4_0.scr54 \
        -in $site_4_0 -x 0 -y 0 -rely 0.185 -width 0 -relwidth 1 -height 0 \
        -relheight 0.8 -anchor nw -bordermode ignore 
    vTcl:copy_lock $site_3_0.lab46
    labelframe $site_3_0.lab47 \
        -font TkDefaultFont -foreground black -text Channels \
        -background {#d9d9d9} -height 165 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 320 
    vTcl:DefineAlias "$site_3_0.lab47" "ChannelFrame" vTcl:WidgetProc "TopLevel" 1
    set site_4_0 $site_3_0.lab47
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_4_0.scr54 \
        -background {#d9d9d9} -height 75 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_4_0.scr54" "Channels" vTcl:WidgetProc "TopLevel" 1

    $site_4_0.scr54.01 configure -background white \
        -disabledforeground #a3a3a3 \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -selectmode single \
        -width 10
    vTcl:copy_lock $site_4_0.scr54
    place $site_4_0.scr54 \
        -in $site_4_0 -x 0 -y 0 -rely 0.185 -width 0 -relwidth 1 -height 0 \
        -relheight 0.8 -anchor nw -bordermode ignore 
    vTcl:copy_lock $site_3_0.lab47
    place $site_3_0.lab43 \
        -in $site_3_0 -x 0 -relx 0.33 -y 0 -width 0 -relwidth 0.31 -height 0 \
        -relheight 0.1 -anchor nw -bordermode ignore 
    place $site_3_0.lab44 \
        -in $site_3_0 -x 0 -y 60 -width 681 -height 108 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 0 -y 290 -width 681 -height 108 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab46 \
        -in $site_3_0 -x 0 -y 410 -width 681 -height 108 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -y 180 -width 681 -height 108 -anchor nw \
        -bordermode ignore 
    button $top.but49 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Open 
    vTcl:DefineAlias "$top.but49" "Switch" vTcl:WidgetProc "TopLevel" 1
    set site_3_0 $top.m50
    menu $site_3_0 \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra42 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 50 -y 20 -width 46 -height 24 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

