#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#    Jan 31, 2019 01:17:44 PM EST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import PlutoConfig_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    PlutoConfig_support.set_Tk_var()
    top = TopLevel (root)
    PlutoConfig_support.init(root, top)
    root.mainloop()

w = None
def create_TopLevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    PlutoConfig_support.set_Tk_var()
    top = TopLevel (w)
    PlutoConfig_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_TopLevel():
    global w
    w.destroy()
    w = None

class TopLevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 
        font9 = "-family {Segoe UI} -size 20 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("673x501+570+173")
        top.title("Pluto Configuration")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.ContextName = tk.Label(top)
        self.ContextName.place(relx=0.253, rely=0.02, height=61, width=214)
        self.ContextName.configure(activebackground="#f9f9f9")
        self.ContextName.configure(activeforeground="black")
        self.ContextName.configure(background="#d9d9d9")
        self.ContextName.configure(disabledforeground="#a3a3a3")
        self.ContextName.configure(font=font9)
        self.ContextName.configure(foreground="#000000")
        self.ContextName.configure(highlightbackground="#d9d9d9")
        self.ContextName.configure(highlightcolor="black")
        self.ContextName.configure(text='''Context Name''')

        self.RXConfigFrame = tk.LabelFrame(top)
        self.RXConfigFrame.place(relx=0.015, rely=0.279, relheight=0.25
                , relwidth=0.969)
        self.RXConfigFrame.configure(relief='groove')
        self.RXConfigFrame.configure(foreground="black")
        self.RXConfigFrame.configure(text='''Receiver''')
        self.RXConfigFrame.configure(background="#d9d9d9")
        self.RXConfigFrame.configure(highlightbackground="#d9d9d9")
        self.RXConfigFrame.configure(highlightcolor="black")
        self.RXConfigFrame.configure(width=652)

        self.RXBandwidthFrame = tk.Frame(self.RXConfigFrame)
        self.RXBandwidthFrame.place(relx=0.46, rely=0.16, relheight=0.28
                , relwidth=0.33, bordermode='ignore')
        self.RXBandwidthFrame.configure(relief='flat')
        self.RXBandwidthFrame.configure(borderwidth="2")
        self.RXBandwidthFrame.configure(background="#d9d9d9")
        self.RXBandwidthFrame.configure(highlightbackground="#d9d9d9")
        self.RXBandwidthFrame.configure(highlightcolor="black")
        self.RXBandwidthFrame.configure(width=215)

        self.RXBandwidthLabel = tk.Label(self.RXBandwidthFrame)
        self.RXBandwidthLabel.place(relx=0.093, rely=0.286, height=21, width=61)
        self.RXBandwidthLabel.configure(activebackground="#f9f9f9")
        self.RXBandwidthLabel.configure(activeforeground="black")
        self.RXBandwidthLabel.configure(background="#d9d9d9")
        self.RXBandwidthLabel.configure(disabledforeground="#a3a3a3")
        self.RXBandwidthLabel.configure(foreground="#000000")
        self.RXBandwidthLabel.configure(highlightbackground="#d9d9d9")
        self.RXBandwidthLabel.configure(highlightcolor="black")
        self.RXBandwidthLabel.configure(text='''Bandwidth''')

        self.RXBandwidthEntry = tk.Entry(self.RXBandwidthFrame)
        self.RXBandwidthEntry.place(relx=0.372, rely=0.286, height=20
                , relwidth=0.437)
        self.RXBandwidthEntry.configure(background="white")
        self.RXBandwidthEntry.configure(disabledforeground="#a3a3a3")
        self.RXBandwidthEntry.configure(font="TkFixedFont")
        self.RXBandwidthEntry.configure(foreground="#000000")
        self.RXBandwidthEntry.configure(highlightbackground="#d9d9d9")
        self.RXBandwidthEntry.configure(highlightcolor="black")
        self.RXBandwidthEntry.configure(insertbackground="black")
        self.RXBandwidthEntry.configure(selectbackground="#c4c4c4")
        self.RXBandwidthEntry.configure(selectforeground="black")
        self.RXBandwidthEntry.configure(textvariable=PlutoConfig_support.rxBandwidth)

        self.RXBandwidthUnit = tk.Label(self.RXBandwidthFrame)
        self.RXBandwidthUnit.place(relx=0.837, rely=0.286, height=21, width=31)
        self.RXBandwidthUnit.configure(activebackground="#f9f9f9")
        self.RXBandwidthUnit.configure(activeforeground="black")
        self.RXBandwidthUnit.configure(background="#d9d9d9")
        self.RXBandwidthUnit.configure(disabledforeground="#a3a3a3")
        self.RXBandwidthUnit.configure(foreground="#000000")
        self.RXBandwidthUnit.configure(highlightbackground="#d9d9d9")
        self.RXBandwidthUnit.configure(highlightcolor="black")
        self.RXBandwidthUnit.configure(text='''MHz''')

        self.RXFrequencyFrame = tk.Frame(self.RXConfigFrame)
        self.RXFrequencyFrame.place(relx=0.031, rely=0.16, relheight=0.36
                , relwidth=0.36, bordermode='ignore')
        self.RXFrequencyFrame.configure(relief='flat')
        self.RXFrequencyFrame.configure(borderwidth="2")
        self.RXFrequencyFrame.configure(background="#d9d9d9")
        self.RXFrequencyFrame.configure(highlightbackground="#d9d9d9")
        self.RXFrequencyFrame.configure(highlightcolor="black")
        self.RXFrequencyFrame.configure(width=235)

        self.RXFrequencyLabel = tk.Label(self.RXFrequencyFrame)
        self.RXFrequencyLabel.place(relx=0.085, rely=0.222, height=21, width=61)
        self.RXFrequencyLabel.configure(activebackground="#f9f9f9")
        self.RXFrequencyLabel.configure(activeforeground="black")
        self.RXFrequencyLabel.configure(background="#d9d9d9")
        self.RXFrequencyLabel.configure(disabledforeground="#a3a3a3")
        self.RXFrequencyLabel.configure(foreground="#000000")
        self.RXFrequencyLabel.configure(highlightbackground="#d9d9d9")
        self.RXFrequencyLabel.configure(highlightcolor="black")
        self.RXFrequencyLabel.configure(text='''Frequency''')

        self.RXFrequencyEntry = tk.Entry(self.RXFrequencyFrame)
        self.RXFrequencyEntry.place(relx=0.426, rely=0.222, height=20
                , relwidth=0.4)
        self.RXFrequencyEntry.configure(background="white")
        self.RXFrequencyEntry.configure(disabledforeground="#a3a3a3")
        self.RXFrequencyEntry.configure(font="TkFixedFont")
        self.RXFrequencyEntry.configure(foreground="#000000")
        self.RXFrequencyEntry.configure(highlightbackground="#d9d9d9")
        self.RXFrequencyEntry.configure(highlightcolor="black")
        self.RXFrequencyEntry.configure(insertbackground="black")
        self.RXFrequencyEntry.configure(selectbackground="#c4c4c4")
        self.RXFrequencyEntry.configure(selectforeground="black")
        self.RXFrequencyEntry.configure(textvariable=PlutoConfig_support.rxFrequency)

        self.RXFrequencyUnit = tk.Label(self.RXFrequencyFrame)
        self.RXFrequencyUnit.place(relx=0.851, rely=0.222, height=21, width=31)
        self.RXFrequencyUnit.configure(activebackground="#f9f9f9")
        self.RXFrequencyUnit.configure(activeforeground="black")
        self.RXFrequencyUnit.configure(background="#d9d9d9")
        self.RXFrequencyUnit.configure(disabledforeground="#a3a3a3")
        self.RXFrequencyUnit.configure(foreground="#000000")
        self.RXFrequencyUnit.configure(highlightbackground="#d9d9d9")
        self.RXFrequencyUnit.configure(highlightcolor="black")
        self.RXFrequencyUnit.configure(text='''MHz''')

        self.RXSamplingFrequencyFrame = tk.Frame(self.RXConfigFrame)
        self.RXSamplingFrequencyFrame.place(relx=0.015, rely=0.56, relheight=0.28
                , relwidth=0.406, bordermode='ignore')
        self.RXSamplingFrequencyFrame.configure(relief='flat')
        self.RXSamplingFrequencyFrame.configure(borderwidth="2")
        self.RXSamplingFrequencyFrame.configure(background="#d9d9d9")
        self.RXSamplingFrequencyFrame.configure(highlightbackground="#d9d9d9")
        self.RXSamplingFrequencyFrame.configure(highlightcolor="black")
        self.RXSamplingFrequencyFrame.configure(width=265)

        self.RXSamplingFrequencyLabel = tk.Label(self.RXSamplingFrequencyFrame)
        self.RXSamplingFrequencyLabel.place(relx=0.0, rely=0.286, height=21
                , width=111)
        self.RXSamplingFrequencyLabel.configure(activebackground="#f9f9f9")
        self.RXSamplingFrequencyLabel.configure(activeforeground="black")
        self.RXSamplingFrequencyLabel.configure(background="#d9d9d9")
        self.RXSamplingFrequencyLabel.configure(disabledforeground="#a3a3a3")
        self.RXSamplingFrequencyLabel.configure(foreground="#000000")
        self.RXSamplingFrequencyLabel.configure(highlightbackground="#d9d9d9")
        self.RXSamplingFrequencyLabel.configure(highlightcolor="black")
        self.RXSamplingFrequencyLabel.configure(text='''Sampling Frequency''')

        self.RXSamplingFrequencyEntry = tk.Entry(self.RXSamplingFrequencyFrame)
        self.RXSamplingFrequencyEntry.place(relx=0.453, rely=0.286, height=20
                , relwidth=0.355)
        self.RXSamplingFrequencyEntry.configure(background="white")
        self.RXSamplingFrequencyEntry.configure(disabledforeground="#a3a3a3")
        self.RXSamplingFrequencyEntry.configure(font="TkFixedFont")
        self.RXSamplingFrequencyEntry.configure(foreground="#000000")
        self.RXSamplingFrequencyEntry.configure(highlightbackground="#d9d9d9")
        self.RXSamplingFrequencyEntry.configure(highlightcolor="black")
        self.RXSamplingFrequencyEntry.configure(insertbackground="black")
        self.RXSamplingFrequencyEntry.configure(selectbackground="#c4c4c4")
        self.RXSamplingFrequencyEntry.configure(selectforeground="black")
        self.RXSamplingFrequencyEntry.configure(textvariable=PlutoConfig_support.rxSamplingFrequency)

        self.RXSamplingFrequencyUnit = tk.Label(self.RXSamplingFrequencyFrame)
        self.RXSamplingFrequencyUnit.place(relx=0.83, rely=0.286, height=21
                , width=31)
        self.RXSamplingFrequencyUnit.configure(activebackground="#f9f9f9")
        self.RXSamplingFrequencyUnit.configure(activeforeground="black")
        self.RXSamplingFrequencyUnit.configure(background="#d9d9d9")
        self.RXSamplingFrequencyUnit.configure(disabledforeground="#a3a3a3")
        self.RXSamplingFrequencyUnit.configure(foreground="#000000")
        self.RXSamplingFrequencyUnit.configure(highlightbackground="#d9d9d9")
        self.RXSamplingFrequencyUnit.configure(highlightcolor="black")
        self.RXSamplingFrequencyUnit.configure(text='''MSPS''')

        self.RXSaveButton = tk.Button(self.RXConfigFrame)
        self.RXSaveButton.place(relx=0.874, rely=0.8, height=24, width=35
                , bordermode='ignore')
        self.RXSaveButton.configure(activebackground="#d9d9d9")
        self.RXSaveButton.configure(activeforeground="#000000")
        self.RXSaveButton.configure(background="#d9d9d9")
        self.RXSaveButton.configure(disabledforeground="#a3a3a3")
        self.RXSaveButton.configure(foreground="#000000")
        self.RXSaveButton.configure(highlightbackground="#d9d9d9")
        self.RXSaveButton.configure(highlightcolor="black")
        self.RXSaveButton.configure(pady="0")
        self.RXSaveButton.configure(text='''Save''')

        self.RXSamplesFrame = tk.Frame(self.RXConfigFrame)
        self.RXSamplesFrame.place(relx=0.414, rely=0.56, relheight=0.36
                , relwidth=0.376, bordermode='ignore')
        self.RXSamplesFrame.configure(relief='flat')
        self.RXSamplesFrame.configure(borderwidth="2")
        self.RXSamplesFrame.configure(background="#d9d9d9")
        self.RXSamplesFrame.configure(highlightbackground="#d9d9d9")
        self.RXSamplesFrame.configure(highlightcolor="black")
        self.RXSamplesFrame.configure(width=245)

        self.RXSampleLabel = tk.Label(self.RXSamplesFrame)
        self.RXSampleLabel.place(relx=0.082, rely=0.222, height=21, width=151)
        self.RXSampleLabel.configure(activebackground="#f9f9f9")
        self.RXSampleLabel.configure(activeforeground="black")
        self.RXSampleLabel.configure(background="#d9d9d9")
        self.RXSampleLabel.configure(disabledforeground="#a3a3a3")
        self.RXSampleLabel.configure(foreground="#000000")
        self.RXSampleLabel.configure(highlightbackground="#d9d9d9")
        self.RXSampleLabel.configure(highlightcolor="black")
        self.RXSampleLabel.configure(text='''Samples to Collect''')
        self.RXSampleLabel.configure(width=151)

        self.RXSamplesEntry = tk.Entry(self.RXSamplesFrame)
        self.RXSamplesEntry.place(relx=0.653, rely=0.222, height=20
                , relwidth=0.384)
        self.RXSamplesEntry.configure(background="white")
        self.RXSamplesEntry.configure(disabledforeground="#a3a3a3")
        self.RXSamplesEntry.configure(font="TkFixedFont")
        self.RXSamplesEntry.configure(foreground="#000000")
        self.RXSamplesEntry.configure(highlightbackground="#d9d9d9")
        self.RXSamplesEntry.configure(highlightcolor="black")
        self.RXSamplesEntry.configure(insertbackground="black")
        self.RXSamplesEntry.configure(selectbackground="#c4c4c4")
        self.RXSamplesEntry.configure(selectforeground="black")
        self.RXSamplesEntry.configure(textvariable=PlutoConfig_support.rxSamples)

        self.TXConfigFrame = tk.LabelFrame(top)
        self.TXConfigFrame.place(relx=0.015, rely=0.539, relheight=0.23
                , relwidth=0.969)
        self.TXConfigFrame.configure(relief='groove')
        self.TXConfigFrame.configure(foreground="black")
        self.TXConfigFrame.configure(text='''Transmitter''')
        self.TXConfigFrame.configure(background="#d9d9d9")
        self.TXConfigFrame.configure(highlightbackground="#d9d9d9")
        self.TXConfigFrame.configure(highlightcolor="black")
        self.TXConfigFrame.configure(width=652)

        self.TXFrequencyFrame = tk.Frame(self.TXConfigFrame)
        self.TXFrequencyFrame.place(relx=0.061, rely=0.261, relheight=0.391
                , relwidth=0.36, bordermode='ignore')
        self.TXFrequencyFrame.configure(relief='flat')
        self.TXFrequencyFrame.configure(borderwidth="2")
        self.TXFrequencyFrame.configure(background="#d9d9d9")
        self.TXFrequencyFrame.configure(highlightbackground="#d9d9d9")
        self.TXFrequencyFrame.configure(highlightcolor="black")
        self.TXFrequencyFrame.configure(width=235)

        self.TXFrequencyLabel = tk.Label(self.TXFrequencyFrame)
        self.TXFrequencyLabel.place(relx=-0.043, rely=0.222, height=21
                , width=111)
        self.TXFrequencyLabel.configure(activebackground="#f9f9f9")
        self.TXFrequencyLabel.configure(activeforeground="black")
        self.TXFrequencyLabel.configure(background="#d9d9d9")
        self.TXFrequencyLabel.configure(disabledforeground="#a3a3a3")
        self.TXFrequencyLabel.configure(foreground="#000000")
        self.TXFrequencyLabel.configure(highlightbackground="#d9d9d9")
        self.TXFrequencyLabel.configure(highlightcolor="black")
        self.TXFrequencyLabel.configure(text='''Frequency''')
        self.TXFrequencyLabel.configure(width=111)

        self.TXFrequencyEntry = tk.Entry(self.TXFrequencyFrame)
        self.TXFrequencyEntry.place(relx=0.383, rely=0.222, height=20
                , relwidth=0.4)
        self.TXFrequencyEntry.configure(background="white")
        self.TXFrequencyEntry.configure(disabledforeground="#a3a3a3")
        self.TXFrequencyEntry.configure(font="TkFixedFont")
        self.TXFrequencyEntry.configure(foreground="#000000")
        self.TXFrequencyEntry.configure(highlightbackground="#d9d9d9")
        self.TXFrequencyEntry.configure(highlightcolor="black")
        self.TXFrequencyEntry.configure(insertbackground="black")
        self.TXFrequencyEntry.configure(selectbackground="#c4c4c4")
        self.TXFrequencyEntry.configure(selectforeground="black")
        self.TXFrequencyEntry.configure(textvariable=PlutoConfig_support.txFrequency)

        self.TXFrequencyUnit = tk.Label(self.TXFrequencyFrame)
        self.TXFrequencyUnit.place(relx=0.809, rely=0.222, height=21, width=41)
        self.TXFrequencyUnit.configure(activebackground="#f9f9f9")
        self.TXFrequencyUnit.configure(activeforeground="black")
        self.TXFrequencyUnit.configure(background="#d9d9d9")
        self.TXFrequencyUnit.configure(disabledforeground="#a3a3a3")
        self.TXFrequencyUnit.configure(foreground="#000000")
        self.TXFrequencyUnit.configure(highlightbackground="#d9d9d9")
        self.TXFrequencyUnit.configure(highlightcolor="black")
        self.TXFrequencyUnit.configure(text='''MHz''')
        self.TXFrequencyUnit.configure(width=41)

        self.TXBandwidthFrame = tk.Frame(self.TXConfigFrame)
        self.TXBandwidthFrame.place(relx=0.445, rely=0.261, relheight=0.304
                , relwidth=0.376, bordermode='ignore')
        self.TXBandwidthFrame.configure(relief='flat')
        self.TXBandwidthFrame.configure(borderwidth="2")
        self.TXBandwidthFrame.configure(background="#d9d9d9")
        self.TXBandwidthFrame.configure(highlightbackground="#d9d9d9")
        self.TXBandwidthFrame.configure(highlightcolor="black")
        self.TXBandwidthFrame.configure(width=245)

        self.TXBandwidthLabel = tk.Label(self.TXBandwidthFrame)
        self.TXBandwidthLabel.place(relx=-0.041, rely=0.286, height=21
                , width=111)
        self.TXBandwidthLabel.configure(activebackground="#f9f9f9")
        self.TXBandwidthLabel.configure(activeforeground="black")
        self.TXBandwidthLabel.configure(background="#d9d9d9")
        self.TXBandwidthLabel.configure(disabledforeground="#a3a3a3")
        self.TXBandwidthLabel.configure(foreground="#000000")
        self.TXBandwidthLabel.configure(highlightbackground="#d9d9d9")
        self.TXBandwidthLabel.configure(highlightcolor="black")
        self.TXBandwidthLabel.configure(text='''Bandwidth''')
        self.TXBandwidthLabel.configure(width=111)

        self.TXBandwidthEntry = tk.Entry(self.TXBandwidthFrame)
        self.TXBandwidthEntry.place(relx=0.408, rely=0.286, height=20
                , relwidth=0.384)
        self.TXBandwidthEntry.configure(background="white")
        self.TXBandwidthEntry.configure(disabledforeground="#a3a3a3")
        self.TXBandwidthEntry.configure(font="TkFixedFont")
        self.TXBandwidthEntry.configure(foreground="#000000")
        self.TXBandwidthEntry.configure(highlightbackground="#d9d9d9")
        self.TXBandwidthEntry.configure(highlightcolor="black")
        self.TXBandwidthEntry.configure(insertbackground="black")
        self.TXBandwidthEntry.configure(selectbackground="#c4c4c4")
        self.TXBandwidthEntry.configure(selectforeground="black")
        self.TXBandwidthEntry.configure(textvariable=PlutoConfig_support.txBandwidth)

        self.TXBandwidthUnit = tk.Label(self.TXBandwidthFrame)
        self.TXBandwidthUnit.place(relx=0.735, rely=0.286, height=21, width=41)
        self.TXBandwidthUnit.configure(activebackground="#f9f9f9")
        self.TXBandwidthUnit.configure(activeforeground="black")
        self.TXBandwidthUnit.configure(background="#d9d9d9")
        self.TXBandwidthUnit.configure(disabledforeground="#a3a3a3")
        self.TXBandwidthUnit.configure(foreground="#000000")
        self.TXBandwidthUnit.configure(highlightbackground="#d9d9d9")
        self.TXBandwidthUnit.configure(highlightcolor="black")
        self.TXBandwidthUnit.configure(text='''MHz''')
        self.TXBandwidthUnit.configure(width=41)

        self.TXSaveButton = tk.Button(self.TXConfigFrame)
        self.TXSaveButton.place(relx=0.874, rely=0.783, height=24, width=35
                , bordermode='ignore')
        self.TXSaveButton.configure(activebackground="#d9d9d9")
        self.TXSaveButton.configure(activeforeground="#000000")
        self.TXSaveButton.configure(background="#d9d9d9")
        self.TXSaveButton.configure(disabledforeground="#a3a3a3")
        self.TXSaveButton.configure(foreground="#000000")
        self.TXSaveButton.configure(highlightbackground="#d9d9d9")
        self.TXSaveButton.configure(highlightcolor="black")
        self.TXSaveButton.configure(pady="0")
        self.TXSaveButton.configure(text='''Save''')

if __name__ == '__main__':
    vp_start_gui()





