#############################################################################
# Generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#  Feb 25, 2019 11:24:18 PM EST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Segoe UI} -size 20 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font9
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#ffffff} -highlightbackground {#ffffff} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 671x509+470+229
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1061
    wm minsize $top 176 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Pluto Configuration"
    vTcl:DefineAlias "$top" "TopLevel" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure Label -background #d9d9d9
    ttk::style configure Label -foreground #000000
    ttk::style configure Label -font TkDefaultFont
    label $top.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Context Name} 
    vTcl:DefineAlias "$top.lab45" "ContextName" vTcl:WidgetProc "TopLevel" 1
    labelframe $top.lab42 \
        -font TkDefaultFont -foreground black -relief ridge -text RX \
        -background {#ffffff} -height 335 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 302 
    vTcl:DefineAlias "$top.lab42" "RXConfigFrame" vTcl:WidgetProc "TopLevel" 1
    set site_3_0 $top.lab42
    frame $site_3_0.fra54 \
        -borderwidth 2 -relief groove -background {#ffffff} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 235 
    vTcl:DefineAlias "$site_3_0.fra54" "RXBandwidthFrame" vTcl:WidgetProc "TopLevel" 1
    set site_4_0 $site_3_0.fra54
    label $site_4_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Bandwidth 
    vTcl:DefineAlias "$site_4_0.lab55" "RXBandwidthLabel" vTcl:WidgetProc "TopLevel" 1
    entry $site_4_0.ent56 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable rxBandwidth 
    vTcl:DefineAlias "$site_4_0.ent56" "RXBandwidthEntry" vTcl:WidgetProc "TopLevel" 1
    label $site_4_0.lab57 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text MHz 
    vTcl:DefineAlias "$site_4_0.lab57" "RXBandwidthUnit" vTcl:WidgetProc "TopLevel" 1
    place $site_4_0.lab55 \
        -in $site_4_0 -x 10 -y 10 -width 61 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent56 \
        -in $site_4_0 -x 110 -y 10 -width 84 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab57 \
        -in $site_4_0 -x 200 -y 10 -width 31 -height 21 -anchor nw \
        -bordermode ignore 
    frame $site_3_0.fra58 \
        -borderwidth 2 -relief groove -background {#ffffff} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 235 
    vTcl:DefineAlias "$site_3_0.fra58" "RXFrequencyFrame" vTcl:WidgetProc "TopLevel" 1
    set site_4_0 $site_3_0.fra58
    label $site_4_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Frequency 
    vTcl:DefineAlias "$site_4_0.lab55" "RXFrequencyLabel" vTcl:WidgetProc "TopLevel" 1
    entry $site_4_0.ent56 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable rxFrequency 
    vTcl:DefineAlias "$site_4_0.ent56" "RXFrequencyEntry" vTcl:WidgetProc "TopLevel" 1
    label $site_4_0.lab57 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text MHz 
    vTcl:DefineAlias "$site_4_0.lab57" "RXFrequencyUnit" vTcl:WidgetProc "TopLevel" 1
    place $site_4_0.lab55 \
        -in $site_4_0 -x 10 -y 10 -width 61 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent56 \
        -in $site_4_0 -x 110 -y 10 -width 84 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab57 \
        -in $site_4_0 -x 200 -y 10 -width 31 -height 21 -anchor nw \
        -bordermode ignore 
    frame $site_3_0.fra66 \
        -borderwidth 2 -relief groove -background {#ffffff} -height 35 \
        -highlightbackground {#ffffff} -highlightcolor black -width 235 
    vTcl:DefineAlias "$site_3_0.fra66" "RXSamplesFrame" vTcl:WidgetProc "TopLevel" 1
    set site_4_0 $site_3_0.fra66
    label $site_4_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Samples 
    vTcl:DefineAlias "$site_4_0.lab55" "RXSampleLabel" vTcl:WidgetProc "TopLevel" 1
    entry $site_4_0.ent56 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable rxSamples 
    vTcl:DefineAlias "$site_4_0.ent56" "RXSamplesEntry" vTcl:WidgetProc "TopLevel" 1
    place $site_4_0.lab55 \
        -in $site_4_0 -x 10 -y 10 -width 51 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent56 \
        -in $site_4_0 -x 110 -y 10 -width 84 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $site_3_0.fra47 \
        -borderwidth 2 -relief groove -background {#ffffff} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 235 
    vTcl:DefineAlias "$site_3_0.fra47" "RXDecimationFrame" vTcl:WidgetProc "TopLevel" 1
    set site_4_0 $site_3_0.fra47
    label $site_4_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Decimation 
    vTcl:DefineAlias "$site_4_0.lab55" "RXDecimationLabel" vTcl:WidgetProc "TopLevel" 1
    entry $site_4_0.ent56 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable rxDecimation 
    vTcl:DefineAlias "$site_4_0.ent56" "RXDecimationEntry" vTcl:WidgetProc "TopLevel" 1
    label $site_4_0.lab57 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text ? 
    vTcl:DefineAlias "$site_4_0.lab57" "RXDecimationUnit" vTcl:WidgetProc "TopLevel" 1
    place $site_4_0.lab55 \
        -in $site_4_0 -x 10 -y 10 -width 61 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent56 \
        -in $site_4_0 -x 110 -y 10 -width 84 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab57 \
        -in $site_4_0 -x 200 -y 10 -width 31 -height 21 -anchor nw \
        -bordermode ignore 
    frame $site_3_0.fra49 \
        -borderwidth 2 -relief groove -background {#ffffff} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 235 
    vTcl:DefineAlias "$site_3_0.fra49" "RXGainFrame" vTcl:WidgetProc "TopLevel" 1
    set site_4_0 $site_3_0.fra49
    label $site_4_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Gain 
    vTcl:DefineAlias "$site_4_0.lab55" "RXGainLabel" vTcl:WidgetProc "TopLevel" 1
    entry $site_4_0.ent56 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable rxGain 
    vTcl:DefineAlias "$site_4_0.ent56" "RXGainEntry" vTcl:WidgetProc "TopLevel" 1
    label $site_4_0.lab57 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text ? 
    vTcl:DefineAlias "$site_4_0.lab57" "RXGainUnit" vTcl:WidgetProc "TopLevel" 1
    place $site_4_0.lab55 \
        -in $site_4_0 -x 10 -y 10 -width 31 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent56 \
        -in $site_4_0 -x 110 -y 10 -width 84 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab57 \
        -in $site_4_0 -x 200 -y 10 -width 31 -height 21 -anchor nw \
        -bordermode ignore 
    frame $site_3_0.fra50 \
        -borderwidth 2 -relief groove -background {#ffffff} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 235 
    vTcl:DefineAlias "$site_3_0.fra50" "RXGainModeFrame" vTcl:WidgetProc "TopLevel" 1
    set site_4_0 $site_3_0.fra50
    label $site_4_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Gain Mode} 
    vTcl:DefineAlias "$site_4_0.lab55" "RXGainModeLabel" vTcl:WidgetProc "TopLevel" 1
    place $site_4_0.lab55 \
        -in $site_4_0 -x 10 -y 10 -width 61 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $site_3_0.fra42 \
        -borderwidth 2 -relief groove -background {#ffffff} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 235 
    vTcl:DefineAlias "$site_3_0.fra42" "RXPlotFrame" vTcl:WidgetProc "TopLevel" 1
    set site_4_0 $site_3_0.fra42
    label $site_4_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Plot 
    vTcl:DefineAlias "$site_4_0.lab55" "RXPlotLabel" vTcl:WidgetProc "TopLevel" 1
    place $site_4_0.lab55 \
        -in $site_4_0 -x 10 -y 10 -width 31 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    checkbutton $site_3_0.che42 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -text Imaginary -variable rxImaginary 
    vTcl:DefineAlias "$site_3_0.che42" "RXImagCheck" vTcl:WidgetProc "TopLevel" 1
    place $site_3_0.fra54 \
        -in $site_3_0 -x 20 -y 50 -width 235 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra58 \
        -in $site_3_0 -x 20 -y 20 -width 235 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra66 \
        -in $site_3_0 -x 20 -y 170 -width 235 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra47 \
        -in $site_3_0 -x 20 -y 80 -width 235 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra49 \
        -in $site_3_0 -x 20 -y 110 -width 235 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra50 \
        -in $site_3_0 -x 20 -y 140 -width 235 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra42 \
        -in $site_3_0 -x 20 -y 200 -width 235 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che42 \
        -in $site_3_0 -x 20 -y 240 -width 231 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $top.lab43 \
        -font TkDefaultFont -foreground black -text TX -background {#ffffff} \
        -height 335 -highlightbackground {#d9d9d9} -highlightcolor black \
        -width 312 
    vTcl:DefineAlias "$top.lab43" "TXConfigFrame" vTcl:WidgetProc "TopLevel" 1
    set site_3_0 $top.lab43
    frame $site_3_0.fra60 \
        -borderwidth 2 -relief groove -background {#ffffff} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 235 
    vTcl:DefineAlias "$site_3_0.fra60" "TXFrequencyFrame" vTcl:WidgetProc "TopLevel" 1
    set site_4_0 $site_3_0.fra60
    label $site_4_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Frequency 
    vTcl:DefineAlias "$site_4_0.lab55" "TXFrequencyLabel" vTcl:WidgetProc "TopLevel" 1
    entry $site_4_0.ent56 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable txFrequency 
    vTcl:DefineAlias "$site_4_0.ent56" "TXFrequencyEntry" vTcl:WidgetProc "TopLevel" 1
    label $site_4_0.lab57 \
        -activebackground {#ffffff} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text MHz 
    vTcl:DefineAlias "$site_4_0.lab57" "TXFrequencyUnit" vTcl:WidgetProc "TopLevel" 1
    place $site_4_0.lab55 \
        -in $site_4_0 -x 10 -y 10 -width 61 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent56 \
        -in $site_4_0 -x 90 -y 10 -width 94 -height 20 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab57 \
        -in $site_4_0 -x 190 -y 10 -width 41 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $site_3_0.fra61 \
        -borderwidth 2 -relief groove -background {#ffffff} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 235 
    vTcl:DefineAlias "$site_3_0.fra61" "TXBandwidthFrame" vTcl:WidgetProc "TopLevel" 1
    set site_4_0 $site_3_0.fra61
    label $site_4_0.lab55 \
        -activebackground {#ffffff} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Bandwidth 
    vTcl:DefineAlias "$site_4_0.lab55" "TXBandwidthLabel" vTcl:WidgetProc "TopLevel" 1
    entry $site_4_0.ent56 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable txBandwidth 
    vTcl:DefineAlias "$site_4_0.ent56" "TXBandwidthEntry" vTcl:WidgetProc "TopLevel" 1
    label $site_4_0.lab57 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text MHz 
    vTcl:DefineAlias "$site_4_0.lab57" "TXBandwidthUnit" vTcl:WidgetProc "TopLevel" 1
    place $site_4_0.lab55 \
        -in $site_4_0 -x 10 -y 10 -width 61 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent56 \
        -in $site_4_0 -x 90 -y 10 -width 94 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab57 \
        -in $site_4_0 -x 190 -y 10 -width 41 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $site_3_0.fra42 \
        -borderwidth 2 -relief groove -background {#ffffff} -height 35 \
        -highlightbackground {#ffffff} -highlightcolor black -width 235 
    vTcl:DefineAlias "$site_3_0.fra42" "TXSamplesFrame" vTcl:WidgetProc "TopLevel" 1
    set site_4_0 $site_3_0.fra42
    label $site_4_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Samples 
    vTcl:DefineAlias "$site_4_0.lab55" "TXSampleLabel" vTcl:WidgetProc "TopLevel" 1
    entry $site_4_0.ent56 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable txSamples 
    vTcl:DefineAlias "$site_4_0.ent56" "TXSamplesEntry" vTcl:WidgetProc "TopLevel" 1
    place $site_4_0.lab55 \
        -in $site_4_0 -x 10 -y 10 -width 51 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent56 \
        -in $site_4_0 -x 90 -y 10 -width 94 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $site_3_0.fra44 \
        -borderwidth 2 -relief groove -background {#ffffff} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 235 
    vTcl:DefineAlias "$site_3_0.fra44" "TXInterpolationFrame" vTcl:WidgetProc "TopLevel" 1
    set site_4_0 $site_3_0.fra44
    label $site_4_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text Interpolation 
    vTcl:DefineAlias "$site_4_0.lab55" "TXInterpolationLabel" vTcl:WidgetProc "TopLevel" 1
    entry $site_4_0.ent56 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable txInterpolation 
    vTcl:DefineAlias "$site_4_0.ent56" "TXInterpolationEntry" vTcl:WidgetProc "TopLevel" 1
    label $site_4_0.lab48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text ? 
    vTcl:DefineAlias "$site_4_0.lab48" "TXInterpolationUnit" vTcl:WidgetProc "TopLevel" 1
    place $site_4_0.lab55 \
        -in $site_4_0 -x 10 -y 10 -width 71 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent56 \
        -in $site_4_0 -x 90 -y 10 -width 94 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab48 \
        -in $site_4_0 -x 190 -y 10 -width 41 -height 21 -anchor nw \
        -bordermode ignore 
    frame $site_3_0.fra59 \
        -borderwidth 2 -relief groove -background {#ffffff} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 235 
    vTcl:DefineAlias "$site_3_0.fra59" "TXGainFrame" vTcl:WidgetProc "TopLevel" 1
    set site_4_0 $site_3_0.fra59
    label $site_4_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Gain 
    vTcl:DefineAlias "$site_4_0.lab55" "TXGainLabel" vTcl:WidgetProc "TopLevel" 1
    entry $site_4_0.ent56 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable txGain 
    vTcl:DefineAlias "$site_4_0.ent56" "TXGainEntry" vTcl:WidgetProc "TopLevel" 1
    label $site_4_0.lab57 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text ? 
    vTcl:DefineAlias "$site_4_0.lab57" "TXGainUnit" vTcl:WidgetProc "TopLevel" 1
    place $site_4_0.lab55 \
        -in $site_4_0 -x 10 -y 10 -width 31 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent56 \
        -in $site_4_0 -x 90 -y 10 -width 94 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab57 \
        -in $site_4_0 -x 200 -y 10 -width 21 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $site_3_0.fra62 \
        -borderwidth 2 -relief groove -background {#ffffff} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 235 
    vTcl:DefineAlias "$site_3_0.fra62" "TXDataFileFrame" vTcl:WidgetProc "TopLevel" 1
    set site_4_0 $site_3_0.fra62
    label $site_4_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Data File} 
    vTcl:DefineAlias "$site_4_0.lab55" "TXDataFileLabel" vTcl:WidgetProc "TopLevel" 1
    entry $site_4_0.ent63 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable txDataFile 
    vTcl:DefineAlias "$site_4_0.ent63" "TXDataFileEntry" vTcl:WidgetProc "TopLevel" 1
    button $site_4_0.but64 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text ... 
    vTcl:DefineAlias "$site_4_0.but64" "TXDataFileButton" vTcl:WidgetProc "TopLevel" 1
    place $site_4_0.lab55 \
        -in $site_4_0 -x 10 -y 10 -width 51 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent63 \
        -in $site_4_0 -x 90 -y 10 -width 94 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but64 \
        -in $site_4_0 -x 0 -relx 0.84 -y 10 -width 27 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $site_3_0.fra43 \
        -borderwidth 2 -relief groove -background {#ffffff} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 235 
    vTcl:DefineAlias "$site_3_0.fra43" "TXPlotFrame" vTcl:WidgetProc "TopLevel" 1
    set site_4_0 $site_3_0.fra43
    label $site_4_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Plot 
    vTcl:DefineAlias "$site_4_0.lab55" "TXPlotLabel" vTcl:WidgetProc "TopLevel" 1
    place $site_4_0.lab55 \
        -in $site_4_0 -x 10 -y 10 -width 31 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    checkbutton $site_3_0.che43 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -text Imaginary -variable txImaginary 
    vTcl:DefineAlias "$site_3_0.che43" "TXImagCheck" vTcl:WidgetProc "TopLevel" 1
    place $site_3_0.fra60 \
        -in $site_3_0 -x 10 -y 20 -width 235 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra61 \
        -in $site_3_0 -x 10 -y 50 -width 235 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra42 \
        -in $site_3_0 -x 10 -y 170 -width 235 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra44 \
        -in $site_3_0 -x 10 -y 80 -width 235 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra59 \
        -in $site_3_0 -x 10 -y 110 -width 235 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra62 \
        -in $site_3_0 -x 10 -y 140 -width 235 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra43 \
        -in $site_3_0 -x 10 -y 200 -width 235 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che43 \
        -in $site_3_0 -x 10 -y 240 -width 231 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra42 \
        -borderwidth 2 -background {#ffffff} -height 35 \
        -highlightbackground {#ffffff} -highlightcolor black -width 265 
    vTcl:DefineAlias "$top.fra42" "SamplingFrequencyFrame" vTcl:WidgetProc "TopLevel" 1
    set site_3_0 $top.fra42
    label $site_3_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Sampling Frequency} 
    vTcl:DefineAlias "$site_3_0.lab55" "SamplingFrequencyLabel" vTcl:WidgetProc "TopLevel" 1
    entry $site_3_0.ent56 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable samplingFrequency 
    vTcl:DefineAlias "$site_3_0.ent56" "SamplingFrequencyEntry" vTcl:WidgetProc "TopLevel" 1
    label $site_3_0.lab57 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text MSPS 
    vTcl:DefineAlias "$site_3_0.lab57" "SamplingFrequencyUnit" vTcl:WidgetProc "TopLevel" 1
    place $site_3_0.lab55 \
        -in $site_3_0 -x 0 -y 10 -width 111 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent56 \
        -in $site_3_0 -x 120 -y 10 -width 94 -height 20 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 220 -y 10 -width 31 -height 21 -anchor nw \
        -bordermode ignore 
    button $top.but43 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Save 
    vTcl:DefineAlias "$top.but43" "SaveButton" vTcl:WidgetProc "TopLevel" 1
    frame $top.fra44 \
        -borderwidth 2 -background {#ffffff} -height 45 \
        -highlightbackground {#ffffff} -highlightcolor black -width 265 
    vTcl:DefineAlias "$top.fra44" "ModulationSchemeFrame" vTcl:WidgetProc "TopLevel" 1
    set site_3_0 $top.fra44
    label $site_3_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Modulation Scheme} 
    vTcl:DefineAlias "$site_3_0.lab55" "ModulationSchemeLabel" vTcl:WidgetProc "TopLevel" 1
    place $site_3_0.lab55 \
        -in $site_3_0 -x 0 -y 10 -width 111 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra45 \
        -borderwidth 2 -background {#ffffff} -height 25 \
        -highlightbackground {#ffffff} -highlightcolor black -width 225 
    vTcl:DefineAlias "$top.fra45" "ThreadUpdateFrame" vTcl:WidgetProc "TopLevel" 1
    set site_3_0 $top.fra45
    label $site_3_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Thread Update} 
    vTcl:DefineAlias "$site_3_0.lab55" "ThreadUpdateLabel" vTcl:WidgetProc "TopLevel" 1
    entry $site_3_0.ent46 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable threadUpdate 
    vTcl:DefineAlias "$site_3_0.ent46" "ThreadUpdateEntry" vTcl:WidgetProc "TopLevel" 1
    label $site_3_0.lab48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text secs 
    vTcl:DefineAlias "$site_3_0.lab48" "ThreadUpdateUnit" vTcl:WidgetProc "TopLevel" 1
    place $site_3_0.lab55 \
        -in $site_3_0 -x 0 -y 0 -width 81 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $site_3_0.ent46 \
        -in $site_3_0 -x 90 -y 0 -width 94 -height 20 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 190 -y 0 -width 31 -height 21 -anchor nw \
        -bordermode ignore 
    frame $top.fra49 \
        -borderwidth 2 -background {#ffffff} -height 25 \
        -highlightbackground {#ffffff} -highlightcolor black -width 225 
    vTcl:DefineAlias "$top.fra49" "PlotUpdateFrame" vTcl:WidgetProc "TopLevel" 1
    set site_3_0 $top.fra49
    label $site_3_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Plot Update} 
    vTcl:DefineAlias "$site_3_0.lab55" "PlotUpdateLabel" vTcl:WidgetProc "TopLevel" 1
    entry $site_3_0.ent46 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable plotUpdate 
    vTcl:DefineAlias "$site_3_0.ent46" "PlotUpdateEntry" vTcl:WidgetProc "TopLevel" 1
    label $site_3_0.lab48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text secs 
    vTcl:DefineAlias "$site_3_0.lab48" "PlotUpdateUnit" vTcl:WidgetProc "TopLevel" 1
    place $site_3_0.lab55 \
        -in $site_3_0 -x 0 -y 0 -width 71 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $site_3_0.ent46 \
        -in $site_3_0 -x 90 -y 0 -width 94 -height 20 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 190 -y 0 -width 31 -height 21 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab45 \
        -in $top -x 220 -y 10 -width 214 -relwidth 0 -height 51 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab42 \
        -in $top -x 27 -relx 0.01 -y 140 -width 302 -relwidth 0 -height 335 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab43 \
        -in $top -x 340 -relx 0.01 -y 140 -width 312 -relwidth 0 -height 335 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.fra42 \
        -in $top -x 40 -y 60 -width 265 -height 35 -anchor nw \
        -bordermode ignore 
    place $top.but43 \
        -in $top -x 610 -y 480 -width 35 -height 24 -anchor nw \
        -bordermode ignore 
    place $top.fra44 \
        -in $top -x 40 -y 90 -width 265 -relwidth 0 -height 45 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra45 \
        -in $top -x 340 -y 70 -width 225 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra49 \
        -in $top -x 340 -y 100 -width 225 -height 25 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

