#############################################################################
# Generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#  Jan 30, 2019 12:33:39 AM EST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Segoe UI} -size 20 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font9
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x450+570+173
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Pluto Configuration"
    vTcl:DefineAlias "$top" "TopLevel" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Context Name} 
    vTcl:DefineAlias "$top.lab45" "ContextName" vTcl:WidgetProc "TopLevel" 1
    labelframe $top.lab42 \
        -font TkDefaultFont -foreground black -text RX -background {#d9d9d9} \
        -height 125 -width 582 
    vTcl:DefineAlias "$top.lab42" "RXConfigFrame" vTcl:WidgetProc "TopLevel" 1
    set site_3_0 $top.lab42
    frame $site_3_0.fra54 \
        -borderwidth 2 -background {#d9d9d9} -height 35 -width 215 
    vTcl:DefineAlias "$site_3_0.fra54" "RXBandwidthFrame" vTcl:WidgetProc "TopLevel" 1
    set site_4_0 $site_3_0.fra54
    label $site_4_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Bandwidth 
    vTcl:DefineAlias "$site_4_0.lab55" "RXBandwidthLabel" vTcl:WidgetProc "TopLevel" 1
    entry $site_4_0.ent56 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable rxBandwidth 
    vTcl:DefineAlias "$site_4_0.ent56" "RXBandwidthEntry" vTcl:WidgetProc "TopLevel" 1
    label $site_4_0.lab57 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text MHz 
    vTcl:DefineAlias "$site_4_0.lab57" "RXBandwidthUnit" vTcl:WidgetProc "TopLevel" 1
    place $site_4_0.lab55 \
        -in $site_4_0 -x 20 -y 10 -width 61 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent56 \
        -in $site_4_0 -x 80 -y 10 -width 94 -height 20 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab57 \
        -in $site_4_0 -x 180 -y 10 -width 31 -height 21 -anchor nw \
        -bordermode ignore 
    frame $site_3_0.fra58 \
        -borderwidth 2 -background {#d9d9d9} -height 45 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 235 
    vTcl:DefineAlias "$site_3_0.fra58" "RXFrequencyFrame" vTcl:WidgetProc "TopLevel" 1
    set site_4_0 $site_3_0.fra58
    label $site_4_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Frequency 
    vTcl:DefineAlias "$site_4_0.lab55" "RXFrequencyLabel" vTcl:WidgetProc "TopLevel" 1
    entry $site_4_0.ent56 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable rxFrequency 
    vTcl:DefineAlias "$site_4_0.ent56" "RXFrequencyEntry" vTcl:WidgetProc "TopLevel" 1
    label $site_4_0.lab57 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text MHz 
    vTcl:DefineAlias "$site_4_0.lab57" "RXFrequencyUnit" vTcl:WidgetProc "TopLevel" 1
    place $site_4_0.lab55 \
        -in $site_4_0 -x 20 -y 10 -width 61 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent56 \
        -in $site_4_0 -x 100 -y 10 -width 94 -height 20 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab57 \
        -in $site_4_0 -x 200 -y 10 -width 31 -height 21 -anchor nw \
        -bordermode ignore 
    frame $site_3_0.fra59 \
        -borderwidth 2 -background {#d9d9d9} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 265 
    vTcl:DefineAlias "$site_3_0.fra59" "RXSamplingFrequencyFrame" vTcl:WidgetProc "TopLevel" 1
    set site_4_0 $site_3_0.fra59
    label $site_4_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Sampling Frequency} 
    vTcl:DefineAlias "$site_4_0.lab55" "RXSamplingFrequencyLabel" vTcl:WidgetProc "TopLevel" 1
    entry $site_4_0.ent56 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable rxSamplingFrequency 
    vTcl:DefineAlias "$site_4_0.ent56" "RXSamplingFrequencyEntry" vTcl:WidgetProc "TopLevel" 1
    label $site_4_0.lab57 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text MSPS 
    vTcl:DefineAlias "$site_4_0.lab57" "RXSamplingFrequencyUnit" vTcl:WidgetProc "TopLevel" 1
    place $site_4_0.lab55 \
        -in $site_4_0 -x 0 -y 10 -width 111 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent56 \
        -in $site_4_0 -x 120 -y 10 -width 94 -height 20 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab57 \
        -in $site_4_0 -x 220 -y 10 -width 31 -height 21 -anchor nw \
        -bordermode ignore 
    button $site_3_0.but65 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Save 
    vTcl:DefineAlias "$site_3_0.but65" "RXSaveButton" vTcl:WidgetProc "TopLevel" 1
    frame $site_3_0.fra66 \
        -borderwidth 2 -background {#d9d9d9} -height 45 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 245 
    vTcl:DefineAlias "$site_3_0.fra66" "RXSamplesFrame" vTcl:WidgetProc "TopLevel" 1
    set site_4_0 $site_3_0.fra66
    label $site_4_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Samples to Collect} 
    vTcl:DefineAlias "$site_4_0.lab55" "RXSampleLabel" vTcl:WidgetProc "TopLevel" 1
    entry $site_4_0.ent56 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable rxSamples 
    vTcl:DefineAlias "$site_4_0.ent56" "RXSamplesEntry" vTcl:WidgetProc "TopLevel" 1
    place $site_4_0.lab55 \
        -in $site_4_0 -x 20 -y 10 -width 111 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent56 \
        -in $site_4_0 -x 130 -y 10 -width 94 -height 20 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra54 \
        -in $site_3_0 -x 300 -y 20 -width 215 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra58 \
        -in $site_3_0 -x 20 -y 20 -width 235 -relwidth 0 -height 45 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra59 \
        -in $site_3_0 -x 10 -y 70 -width 265 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but65 \
        -in $site_3_0 -x 520 -y 100 -width 35 -height 24 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra66 \
        -in $site_3_0 -x 270 -y 70 -width 245 -relwidth 0 -height 45 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $top.lab43 \
        -font TkDefaultFont -foreground black -text TX -background {#d9d9d9} \
        -height 115 -highlightbackground {#d9d9d9} -highlightcolor black \
        -width 582 
    vTcl:DefineAlias "$top.lab43" "TXConfigFrame" vTcl:WidgetProc "TopLevel" 1
    set site_3_0 $top.lab43
    frame $site_3_0.fra60 \
        -borderwidth 2 -background {#d9d9d9} -height 45 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 215 
    vTcl:DefineAlias "$site_3_0.fra60" "TXFrequencyFrame" vTcl:WidgetProc "TopLevel" 1
    set site_4_0 $site_3_0.fra60
    label $site_4_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Frequency 
    vTcl:DefineAlias "$site_4_0.lab55" "TXFrequencyLabel" vTcl:WidgetProc "TopLevel" 1
    entry $site_4_0.ent56 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable txFrequency 
    vTcl:DefineAlias "$site_4_0.ent56" "TXFrequencyEntry" vTcl:WidgetProc "TopLevel" 1
    label $site_4_0.lab57 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text MHz 
    vTcl:DefineAlias "$site_4_0.lab57" "TXFrequencyUnit" vTcl:WidgetProc "TopLevel" 1
    place $site_4_0.lab55 \
        -in $site_4_0 -x 10 -y 10 -width 61 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent56 \
        -in $site_4_0 -x 70 -y 10 -width 94 -height 20 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab57 \
        -in $site_4_0 -x 170 -y 10 -width 31 -height 21 -anchor nw \
        -bordermode ignore 
    frame $site_3_0.fra61 \
        -borderwidth 2 -background {#d9d9d9} -height 35 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 215 
    vTcl:DefineAlias "$site_3_0.fra61" "TXBandwidthFrame" vTcl:WidgetProc "TopLevel" 1
    set site_4_0 $site_3_0.fra61
    label $site_4_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Bandwidth 
    vTcl:DefineAlias "$site_4_0.lab55" "TXBandwidthLabel" vTcl:WidgetProc "TopLevel" 1
    entry $site_4_0.ent56 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable txBandwidth 
    vTcl:DefineAlias "$site_4_0.ent56" "TXBandwidthEntry" vTcl:WidgetProc "TopLevel" 1
    label $site_4_0.lab57 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text MHz 
    vTcl:DefineAlias "$site_4_0.lab57" "TXBandwidthUnit" vTcl:WidgetProc "TopLevel" 1
    place $site_4_0.lab55 \
        -in $site_4_0 -x 20 -y 10 -width 61 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent56 \
        -in $site_4_0 -x 80 -y 10 -width 94 -height 20 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab57 \
        -in $site_4_0 -x 180 -y 10 -width 31 -height 21 -anchor nw \
        -bordermode ignore 
    button $site_3_0.but64 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Save 
    vTcl:DefineAlias "$site_3_0.but64" "TXSaveButton" vTcl:WidgetProc "TopLevel" 1
    place $site_3_0.fra60 \
        -in $site_3_0 -x 60 -y 30 -width 215 -relwidth 0 -height 45 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra61 \
        -in $site_3_0 -x 290 -y 30 -width 215 -height 35 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but64 \
        -in $site_3_0 -x 520 -y 90 -width 35 -height 24 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab45 \
        -in $top -x 170 -y 10 -width 214 -relwidth 0 -height 61 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab42 \
        -in $top -x 0 -relx 0.01 -y 140 -width 582 -relwidth 0 -height 125 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab43 \
        -in $top -x 0 -relx 0.01 -y 270 -width 582 -relwidth 0 -height 115 \
        -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

