#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#    Apr 11, 2019 05:16:33 PM EDT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Throughput_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    Throughput_support.set_Tk_var()
    top = Throughput_TL (root)
    Throughput_support.init(root, top)
    root.mainloop()

w = None
def create_Throughput_TL(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    Throughput_support.set_Tk_var()
    top = Throughput_TL (w)
    Throughput_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Throughput_TL():
    global w
    w.destroy()
    w = None

class Throughput_TL:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI} -size 9 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 12 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("600x450+651+212")
        top.title("Throughput Analysis")
        top.configure(background="#ffffff")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Title = tk.Label(top)
        self.Title.place(relx=0.067, rely=0.044, height=31, width=174)
        self.Title.configure(activebackground="#f9f9f9")
        self.Title.configure(activeforeground="black")
        self.Title.configure(background="#ffffff")
        self.Title.configure(disabledforeground="#a3a3a3")
        self.Title.configure(font=font9)
        self.Title.configure(foreground="#000000")
        self.Title.configure(highlightbackground="#d9d9d9")
        self.Title.configure(highlightcolor="black")
        self.Title.configure(text='''Throughput Analysis''')

        self.StartButton = tk.Button(top)
        self.StartButton.place(relx=0.35, rely=0.044, height=34, width=77)
        self.StartButton.configure(activebackground="#d9d9d9")
        self.StartButton.configure(activeforeground="#000000")
        self.StartButton.configure(background="#d9d9d9")
        self.StartButton.configure(disabledforeground="#a3a3a3")
        self.StartButton.configure(foreground="#000000")
        self.StartButton.configure(highlightbackground="#d9d9d9")
        self.StartButton.configure(highlightcolor="black")
        self.StartButton.configure(pady="0")
        self.StartButton.configure(text='''Start''')

        self.StopButton = tk.Button(top)
        self.StopButton.place(relx=0.5, rely=0.044, height=34, width=77)
        self.StopButton.configure(activebackground="#d9d9d9")
        self.StopButton.configure(activeforeground="#000000")
        self.StopButton.configure(background="#d9d9d9")
        self.StopButton.configure(disabledforeground="#a3a3a3")
        self.StopButton.configure(foreground="#000000")
        self.StopButton.configure(highlightbackground="#d9d9d9")
        self.StopButton.configure(highlightcolor="black")
        self.StopButton.configure(pady="0")
        self.StopButton.configure(text='''Stop''')

        self.vpr_label = tk.Label(top)
        self.vpr_label.place(relx=0.033, rely=0.356, height=31, width=124)
        self.vpr_label.configure(activebackground="#f9f9f9")
        self.vpr_label.configure(activeforeground="black")
        self.vpr_label.configure(background="#ffffff")
        self.vpr_label.configure(disabledforeground="#a3a3a3")
        self.vpr_label.configure(font=font10)
        self.vpr_label.configure(foreground="#000000")
        self.vpr_label.configure(highlightbackground="#d9d9d9")
        self.vpr_label.configure(highlightcolor="black")
        self.vpr_label.configure(text='''Valid Packet Ratio''')

        self.tThroughput_label = tk.Label(top)
        self.tThroughput_label.place(relx=0.517, rely=0.533, height=31
                , width=144)
        self.tThroughput_label.configure(activebackground="#f9f9f9")
        self.tThroughput_label.configure(activeforeground="black")
        self.tThroughput_label.configure(background="#ffffff")
        self.tThroughput_label.configure(disabledforeground="#a3a3a3")
        self.tThroughput_label.configure(font=font10)
        self.tThroughput_label.configure(foreground="#000000")
        self.tThroughput_label.configure(highlightbackground="#d9d9d9")
        self.tThroughput_label.configure(highlightcolor="black")
        self.tThroughput_label.configure(text='''Theoretical Throughput''')

        self.throughput_label = tk.Label(top)
        self.throughput_label.place(relx=0.033, rely=0.444, height=31, width=124)

        self.throughput_label.configure(activebackground="#f9f9f9")
        self.throughput_label.configure(activeforeground="black")
        self.throughput_label.configure(background="#ffffff")
        self.throughput_label.configure(disabledforeground="#a3a3a3")
        self.throughput_label.configure(font=font10)
        self.throughput_label.configure(foreground="#000000")
        self.throughput_label.configure(highlightbackground="#d9d9d9")
        self.throughput_label.configure(highlightcolor="black")
        self.throughput_label.configure(text='''Throughput''')

        self.processingTime_label = tk.Label(top)
        self.processingTime_label.place(relx=0.033, rely=0.533, height=31
                , width=124)
        self.processingTime_label.configure(activebackground="#f9f9f9")
        self.processingTime_label.configure(activeforeground="black")
        self.processingTime_label.configure(background="#ffffff")
        self.processingTime_label.configure(disabledforeground="#a3a3a3")
        self.processingTime_label.configure(font=font10)
        self.processingTime_label.configure(foreground="#000000")
        self.processingTime_label.configure(highlightbackground="#d9d9d9")
        self.processingTime_label.configure(highlightcolor="black")
        self.processingTime_label.configure(text='''Processing Time''')

        self.perPacketTime_label = tk.Label(top)
        self.perPacketTime_label.place(relx=0.033, rely=0.622, height=31
                , width=124)
        self.perPacketTime_label.configure(activebackground="#f9f9f9")
        self.perPacketTime_label.configure(activeforeground="black")
        self.perPacketTime_label.configure(background="#ffffff")
        self.perPacketTime_label.configure(disabledforeground="#a3a3a3")
        self.perPacketTime_label.configure(font=font10)
        self.perPacketTime_label.configure(foreground="#000000")
        self.perPacketTime_label.configure(highlightbackground="#d9d9d9")
        self.perPacketTime_label.configure(highlightcolor="black")
        self.perPacketTime_label.configure(text='''Per Packet Time''')

        self.tPerPacketTime_label = tk.Label(top)
        self.tPerPacketTime_label.place(relx=0.517, rely=0.622, height=31
                , width=144)
        self.tPerPacketTime_label.configure(activebackground="#f9f9f9")
        self.tPerPacketTime_label.configure(activeforeground="black")
        self.tPerPacketTime_label.configure(background="#ffffff")
        self.tPerPacketTime_label.configure(disabledforeground="#a3a3a3")
        self.tPerPacketTime_label.configure(font=font10)
        self.tPerPacketTime_label.configure(foreground="#000000")
        self.tPerPacketTime_label.configure(highlightbackground="#d9d9d9")
        self.tPerPacketTime_label.configure(highlightcolor="black")
        self.tPerPacketTime_label.configure(text='''Theoretical Packet Time''')

        self.vpr_value = tk.Label(top)
        self.vpr_value.place(relx=0.25, rely=0.356, height=31, width=124)
        self.vpr_value.configure(activebackground="#f9f9f9")
        self.vpr_value.configure(activeforeground="black")
        self.vpr_value.configure(background="#ffffff")
        self.vpr_value.configure(disabledforeground="#a3a3a3")
        self.vpr_value.configure(font=font10)
        self.vpr_value.configure(foreground="#000000")
        self.vpr_value.configure(highlightbackground="#d9d9d9")
        self.vpr_value.configure(highlightcolor="black")
        self.vpr_value.configure(relief='ridge')
        self.vpr_value.configure(text='''...''')
        self.vpr_value.configure(textvariable=Throughput_support.vpr_value)

        self.throughput_value = tk.Label(top)
        self.throughput_value.place(relx=0.25, rely=0.444, height=31, width=124)
        self.throughput_value.configure(activebackground="#f9f9f9")
        self.throughput_value.configure(activeforeground="black")
        self.throughput_value.configure(background="#ffffff")
        self.throughput_value.configure(disabledforeground="#a3a3a3")
        self.throughput_value.configure(font=font10)
        self.throughput_value.configure(foreground="#000000")
        self.throughput_value.configure(highlightbackground="#d9d9d9")
        self.throughput_value.configure(highlightcolor="black")
        self.throughput_value.configure(relief='ridge')
        self.throughput_value.configure(text='''...''')
        self.throughput_value.configure(textvariable=Throughput_support.throughput_value)

        self.processingTime_value = tk.Label(top)
        self.processingTime_value.place(relx=0.25, rely=0.533, height=31
                , width=124)
        self.processingTime_value.configure(activebackground="#f9f9f9")
        self.processingTime_value.configure(activeforeground="black")
        self.processingTime_value.configure(background="#ffffff")
        self.processingTime_value.configure(disabledforeground="#a3a3a3")
        self.processingTime_value.configure(font=font10)
        self.processingTime_value.configure(foreground="#000000")
        self.processingTime_value.configure(highlightbackground="#d9d9d9")
        self.processingTime_value.configure(highlightcolor="black")
        self.processingTime_value.configure(relief='ridge')
        self.processingTime_value.configure(text='''...''')
        self.processingTime_value.configure(textvariable=Throughput_support.processingTime_value)

        self.perPacketTime_value = tk.Label(top)
        self.perPacketTime_value.place(relx=0.25, rely=0.622, height=31
                , width=124)
        self.perPacketTime_value.configure(activebackground="#f9f9f9")
        self.perPacketTime_value.configure(activeforeground="black")
        self.perPacketTime_value.configure(background="#ffffff")
        self.perPacketTime_value.configure(disabledforeground="#a3a3a3")
        self.perPacketTime_value.configure(font=font10)
        self.perPacketTime_value.configure(foreground="#000000")
        self.perPacketTime_value.configure(highlightbackground="#d9d9d9")
        self.perPacketTime_value.configure(highlightcolor="black")
        self.perPacketTime_value.configure(relief='ridge')
        self.perPacketTime_value.configure(text='''...''')
        self.perPacketTime_value.configure(textvariable=Throughput_support.perPacket_value)

        self.tThroughput_value = tk.Label(top)
        self.tThroughput_value.place(relx=0.75, rely=0.533, height=31, width=124)

        self.tThroughput_value.configure(activebackground="#f9f9f9")
        self.tThroughput_value.configure(activeforeground="black")
        self.tThroughput_value.configure(background="#ffffff")
        self.tThroughput_value.configure(disabledforeground="#a3a3a3")
        self.tThroughput_value.configure(font=font10)
        self.tThroughput_value.configure(foreground="#000000")
        self.tThroughput_value.configure(highlightbackground="#d9d9d9")
        self.tThroughput_value.configure(highlightcolor="black")
        self.tThroughput_value.configure(relief='ridge')
        self.tThroughput_value.configure(text='''...''')
        self.tThroughput_value.configure(textvariable=Throughput_support.tThroughput_value)

        self.tPerPacketTime_value = tk.Label(top)
        self.tPerPacketTime_value.place(relx=0.75, rely=0.622, height=31
                , width=124)
        self.tPerPacketTime_value.configure(activebackground="#f9f9f9")
        self.tPerPacketTime_value.configure(activeforeground="black")
        self.tPerPacketTime_value.configure(background="#ffffff")
        self.tPerPacketTime_value.configure(disabledforeground="#a3a3a3")
        self.tPerPacketTime_value.configure(font=font10)
        self.tPerPacketTime_value.configure(foreground="#000000")
        self.tPerPacketTime_value.configure(highlightbackground="#d9d9d9")
        self.tPerPacketTime_value.configure(highlightcolor="black")
        self.tPerPacketTime_value.configure(relief='ridge')
        self.tPerPacketTime_value.configure(text='''...''')
        self.tPerPacketTime_value.configure(textvariable=Throughput_support.tPerPacket_value)

        self.validPackets_label = tk.Label(top)
        self.validPackets_label.place(relx=0.533, rely=0.356, height=31
                , width=124)
        self.validPackets_label.configure(activebackground="#f9f9f9")
        self.validPackets_label.configure(activeforeground="black")
        self.validPackets_label.configure(background="#ffffff")
        self.validPackets_label.configure(disabledforeground="#a3a3a3")
        self.validPackets_label.configure(font=font10)
        self.validPackets_label.configure(foreground="#000000")
        self.validPackets_label.configure(highlightbackground="#d9d9d9")
        self.validPackets_label.configure(highlightcolor="black")
        self.validPackets_label.configure(text='''Valid Packets''')

        self.totalPackets_label = tk.Label(top)
        self.totalPackets_label.place(relx=0.533, rely=0.444, height=31
                , width=124)
        self.totalPackets_label.configure(activebackground="#f9f9f9")
        self.totalPackets_label.configure(activeforeground="black")
        self.totalPackets_label.configure(background="#ffffff")
        self.totalPackets_label.configure(disabledforeground="#a3a3a3")
        self.totalPackets_label.configure(font=font10)
        self.totalPackets_label.configure(foreground="#000000")
        self.totalPackets_label.configure(highlightbackground="#d9d9d9")
        self.totalPackets_label.configure(highlightcolor="black")
        self.totalPackets_label.configure(text='''Total Packets''')

        self.validPackets_value = tk.Label(top)
        self.validPackets_value.place(relx=0.75, rely=0.356, height=31
                , width=124)
        self.validPackets_value.configure(activebackground="#f9f9f9")
        self.validPackets_value.configure(activeforeground="black")
        self.validPackets_value.configure(background="#ffffff")
        self.validPackets_value.configure(disabledforeground="#a3a3a3")
        self.validPackets_value.configure(font=font10)
        self.validPackets_value.configure(foreground="#000000")
        self.validPackets_value.configure(highlightbackground="#d9d9d9")
        self.validPackets_value.configure(highlightcolor="black")
        self.validPackets_value.configure(relief='ridge')
        self.validPackets_value.configure(text='''...''')
        self.validPackets_value.configure(textvariable=Throughput_support.validPackets_value)

        self.totalPackets_value = tk.Label(top)
        self.totalPackets_value.place(relx=0.75, rely=0.444, height=31
                , width=124)
        self.totalPackets_value.configure(activebackground="#f9f9f9")
        self.totalPackets_value.configure(activeforeground="black")
        self.totalPackets_value.configure(background="#ffffff")
        self.totalPackets_value.configure(disabledforeground="#a3a3a3")
        self.totalPackets_value.configure(font=font10)
        self.totalPackets_value.configure(foreground="#000000")
        self.totalPackets_value.configure(highlightbackground="#d9d9d9")
        self.totalPackets_value.configure(highlightcolor="black")
        self.totalPackets_value.configure(relief='ridge')
        self.totalPackets_value.configure(text='''...''')
        self.totalPackets_value.configure(textvariable=Throughput_support.totalPackets_value)

        self.msgSize_label = tk.Label(top)
        self.msgSize_label.place(relx=0.067, rely=0.156, height=31, width=84)
        self.msgSize_label.configure(activebackground="#f9f9f9")
        self.msgSize_label.configure(activeforeground="black")
        self.msgSize_label.configure(background="#ffffff")
        self.msgSize_label.configure(disabledforeground="#a3a3a3")
        self.msgSize_label.configure(font=font10)
        self.msgSize_label.configure(foreground="#000000")
        self.msgSize_label.configure(highlightbackground="#d9d9d9")
        self.msgSize_label.configure(highlightcolor="black")
        self.msgSize_label.configure(text='''Message Size''')

        self.guiUpdate_label = tk.Label(top)
        self.guiUpdate_label.place(relx=0.55, rely=0.156, height=31, width=104)
        self.guiUpdate_label.configure(activebackground="#f9f9f9")
        self.guiUpdate_label.configure(activeforeground="black")
        self.guiUpdate_label.configure(background="#ffffff")
        self.guiUpdate_label.configure(disabledforeground="#a3a3a3")
        self.guiUpdate_label.configure(font=font10)
        self.guiUpdate_label.configure(foreground="#000000")
        self.guiUpdate_label.configure(highlightbackground="#d9d9d9")
        self.guiUpdate_label.configure(highlightcolor="black")
        self.guiUpdate_label.configure(text='''GUI Update Time''')

        self.MsgSize_entry = tk.Entry(top)
        self.MsgSize_entry.place(relx=0.25, rely=0.156, height=30, relwidth=0.19)

        self.MsgSize_entry.configure(background="white")
        self.MsgSize_entry.configure(disabledforeground="#a3a3a3")
        self.MsgSize_entry.configure(font="TkFixedFont")
        self.MsgSize_entry.configure(foreground="#000000")
        self.MsgSize_entry.configure(highlightbackground="#d9d9d9")
        self.MsgSize_entry.configure(highlightcolor="black")
        self.MsgSize_entry.configure(insertbackground="black")
        self.MsgSize_entry.configure(justify='center')
        self.MsgSize_entry.configure(relief='groove')
        self.MsgSize_entry.configure(selectbackground="#c4c4c4")
        self.MsgSize_entry.configure(selectforeground="black")
        self.MsgSize_entry.configure(textvariable=Throughput_support.msgSize_value)

        self.GUIUpdate_Entry = tk.Entry(top)
        self.GUIUpdate_Entry.place(relx=0.75, rely=0.156, height=30
                , relwidth=0.19)
        self.GUIUpdate_Entry.configure(background="white")
        self.GUIUpdate_Entry.configure(disabledforeground="#a3a3a3")
        self.GUIUpdate_Entry.configure(font="TkFixedFont")
        self.GUIUpdate_Entry.configure(foreground="#000000")
        self.GUIUpdate_Entry.configure(highlightbackground="#d9d9d9")
        self.GUIUpdate_Entry.configure(highlightcolor="black")
        self.GUIUpdate_Entry.configure(insertbackground="black")
        self.GUIUpdate_Entry.configure(justify='center')
        self.GUIUpdate_Entry.configure(relief='groove')
        self.GUIUpdate_Entry.configure(selectbackground="#c4c4c4")
        self.GUIUpdate_Entry.configure(selectforeground="black")
        self.GUIUpdate_Entry.configure(textvariable=Throughput_support.guiUpdate_value)

        self.adjustedRXSamples_value = tk.Label(top)
        self.adjustedRXSamples_value.place(relx=0.25, rely=0.711, height=31
                , width=124)
        self.adjustedRXSamples_value.configure(activebackground="#f9f9f9")
        self.adjustedRXSamples_value.configure(activeforeground="black")
        self.adjustedRXSamples_value.configure(background="#ffffff")
        self.adjustedRXSamples_value.configure(disabledforeground="#a3a3a3")
        self.adjustedRXSamples_value.configure(font=font10)
        self.adjustedRXSamples_value.configure(foreground="#000000")
        self.adjustedRXSamples_value.configure(highlightbackground="#d9d9d9")
        self.adjustedRXSamples_value.configure(highlightcolor="black")
        self.adjustedRXSamples_value.configure(relief='ridge')
        self.adjustedRXSamples_value.configure(text='''...''')
        self.adjustedRXSamples_value.configure(textvariable=Throughput_support.adjustedRXSamples_value)

        self.adjustedRXSamples_label = tk.Label(top)
        self.adjustedRXSamples_label.place(relx=0.033, rely=0.711, height=31
                , width=124)
        self.adjustedRXSamples_label.configure(activebackground="#f9f9f9")
        self.adjustedRXSamples_label.configure(activeforeground="black")
        self.adjustedRXSamples_label.configure(background="#ffffff")
        self.adjustedRXSamples_label.configure(disabledforeground="#a3a3a3")
        self.adjustedRXSamples_label.configure(font=font10)
        self.adjustedRXSamples_label.configure(foreground="#000000")
        self.adjustedRXSamples_label.configure(highlightbackground="#d9d9d9")
        self.adjustedRXSamples_label.configure(highlightcolor="black")
        self.adjustedRXSamples_label.configure(text='''Adjusted RX Samples''')

        self.startingRXSamples_label = tk.Label(top)
        self.startingRXSamples_label.place(relx=0.033, rely=0.244, height=31
                , width=124)
        self.startingRXSamples_label.configure(activebackground="#f9f9f9")
        self.startingRXSamples_label.configure(activeforeground="black")
        self.startingRXSamples_label.configure(background="#ffffff")
        self.startingRXSamples_label.configure(disabledforeground="#a3a3a3")
        self.startingRXSamples_label.configure(font=font10)
        self.startingRXSamples_label.configure(foreground="#000000")
        self.startingRXSamples_label.configure(highlightbackground="#d9d9d9")
        self.startingRXSamples_label.configure(highlightcolor="black")
        self.startingRXSamples_label.configure(text='''Starting RX Samples''')

        self.StartingRXSamples_Entry = tk.Entry(top)
        self.StartingRXSamples_Entry.place(relx=0.25, rely=0.244, height=30
                , relwidth=0.19)
        self.StartingRXSamples_Entry.configure(background="white")
        self.StartingRXSamples_Entry.configure(disabledforeground="#a3a3a3")
        self.StartingRXSamples_Entry.configure(font="TkFixedFont")
        self.StartingRXSamples_Entry.configure(foreground="#000000")
        self.StartingRXSamples_Entry.configure(highlightbackground="#d9d9d9")
        self.StartingRXSamples_Entry.configure(highlightcolor="black")
        self.StartingRXSamples_Entry.configure(insertbackground="black")
        self.StartingRXSamples_Entry.configure(justify='center')
        self.StartingRXSamples_Entry.configure(relief='groove')
        self.StartingRXSamples_Entry.configure(selectbackground="#c4c4c4")
        self.StartingRXSamples_Entry.configure(selectforeground="black")
        self.StartingRXSamples_Entry.configure(textvariable=Throughput_support.startingRXSample_value)

        self.Checkbutton1 = tk.Checkbutton(top)
        self.Checkbutton1.place(relx=0.567, rely=0.244, relheight=0.056
                , relwidth=0.335)
        self.Checkbutton1.configure(activebackground="#d9d9d9")
        self.Checkbutton1.configure(activeforeground="#000000")
        self.Checkbutton1.configure(background="#ffffff")
        self.Checkbutton1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1.configure(foreground="#000000")
        self.Checkbutton1.configure(highlightbackground="#d9d9d9")
        self.Checkbutton1.configure(highlightcolor="black")
        self.Checkbutton1.configure(justify='left')
        self.Checkbutton1.configure(text='''Dynamically Adjust RX Samples''')
        self.Checkbutton1.configure(variable=Throughput_support.dynamicAdjust)
        self.Checkbutton1.configure(width=201)

if __name__ == '__main__':
    vp_start_gui()





