#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#    Mar 18, 2019 02:13:36 PM EDT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import tictactoe_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    tictactoe_support.set_Tk_var()
    top = TicTacToeTL (root)
    tictactoe_support.init(root, top)
    root.mainloop()

w = None
def create_TicTacToeTL(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    tictactoe_support.set_Tk_var()
    top = TicTacToeTL (w)
    tictactoe_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_TicTacToeTL():
    global w
    w.destroy()
    w = None

class TicTacToeTL:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 
        font10 = "-family {Segoe UI} -size 18 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("600x511+540+159")
        top.title("Tic Tac Toe")
        top.configure(background="#ffffff")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.b0 = tk.Button(top)
        self.b0.place(relx=0.05, rely=0.176, height=135, width=180)
        self.b0.configure(activebackground="#d9d9d9")
        self.b0.configure(activeforeground="#000000")
        self.b0.configure(background="#d9d9d9")
        self.b0.configure(disabledforeground="#a3a3a3")
        self.b0.configure(foreground="#000000")
        self.b0.configure(highlightbackground="#d9d9d9")
        self.b0.configure(highlightcolor="black")
        self.b0.configure(pady="0")
        self.b0.configure(relief='groove')
        self.b0.configure(text='''Button''')
        self.b0.configure(textvariable=tictactoe_support.b0)

        self.b3 = tk.Button(top)
        self.b3.place(relx=0.05, rely=0.431, height=135, width=180)
        self.b3.configure(activebackground="#d9d9d9")
        self.b3.configure(activeforeground="#000000")
        self.b3.configure(background="#d9d9d9")
        self.b3.configure(disabledforeground="#a3a3a3")
        self.b3.configure(foreground="#000000")
        self.b3.configure(highlightbackground="#d9d9d9")
        self.b3.configure(highlightcolor="black")
        self.b3.configure(pady="0")
        self.b3.configure(relief='groove')
        self.b3.configure(text='''Button''')
        self.b3.configure(textvariable=tictactoe_support.b3)

        self.b4 = tk.Button(top)
        self.b4.place(relx=0.35, rely=0.431, height=135, width=180)
        self.b4.configure(activebackground="#d9d9d9")
        self.b4.configure(activeforeground="#000000")
        self.b4.configure(background="#d9d9d9")
        self.b4.configure(disabledforeground="#a3a3a3")
        self.b4.configure(foreground="#000000")
        self.b4.configure(highlightbackground="#d9d9d9")
        self.b4.configure(highlightcolor="black")
        self.b4.configure(pady="0")
        self.b4.configure(relief='groove')
        self.b4.configure(text='''Button''')
        self.b4.configure(textvariable=tictactoe_support.b4)

        self.b1 = tk.Button(top)
        self.b1.place(relx=0.35, rely=0.176, height=135, width=180)
        self.b1.configure(activebackground="#d9d9d9")
        self.b1.configure(activeforeground="#000000")
        self.b1.configure(background="#d9d9d9")
        self.b1.configure(disabledforeground="#a3a3a3")
        self.b1.configure(foreground="#000000")
        self.b1.configure(highlightbackground="#d9d9d9")
        self.b1.configure(highlightcolor="black")
        self.b1.configure(pady="0")
        self.b1.configure(relief='groove')
        self.b1.configure(text='''Button''')
        self.b1.configure(textvariable=tictactoe_support.b1)

        self.b2 = tk.Button(top)
        self.b2.place(relx=0.65, rely=0.176, height=135, width=180)
        self.b2.configure(activebackground="#d9d9d9")
        self.b2.configure(activeforeground="#000000")
        self.b2.configure(background="#d9d9d9")
        self.b2.configure(disabledforeground="#a3a3a3")
        self.b2.configure(foreground="#000000")
        self.b2.configure(highlightbackground="#d9d9d9")
        self.b2.configure(highlightcolor="black")
        self.b2.configure(pady="0")
        self.b2.configure(relief='groove')
        self.b2.configure(text='''Button''')
        self.b2.configure(textvariable=tictactoe_support.b2)

        self.b5 = tk.Button(top)
        self.b5.place(relx=0.65, rely=0.431, height=135, width=180)
        self.b5.configure(activebackground="#d9d9d9")
        self.b5.configure(activeforeground="#000000")
        self.b5.configure(background="#d9d9d9")
        self.b5.configure(disabledforeground="#a3a3a3")
        self.b5.configure(foreground="#000000")
        self.b5.configure(highlightbackground="#d9d9d9")
        self.b5.configure(highlightcolor="black")
        self.b5.configure(pady="0")
        self.b5.configure(relief='groove')
        self.b5.configure(text='''Button''')
        self.b5.configure(textvariable=tictactoe_support.b5)

        self.b6 = tk.Button(top)
        self.b6.place(relx=0.05, rely=0.685, height=135, width=180)
        self.b6.configure(activebackground="#d9d9d9")
        self.b6.configure(activeforeground="#000000")
        self.b6.configure(background="#d9d9d9")
        self.b6.configure(disabledforeground="#a3a3a3")
        self.b6.configure(foreground="#000000")
        self.b6.configure(highlightbackground="#d9d9d9")
        self.b6.configure(highlightcolor="black")
        self.b6.configure(pady="0")
        self.b6.configure(relief='groove')
        self.b6.configure(text='''Button''')
        self.b6.configure(textvariable=tictactoe_support.b6)

        self.b7 = tk.Button(top)
        self.b7.place(relx=0.35, rely=0.685, height=135, width=180)
        self.b7.configure(activebackground="#d9d9d9")
        self.b7.configure(activeforeground="#000000")
        self.b7.configure(background="#d9d9d9")
        self.b7.configure(disabledforeground="#a3a3a3")
        self.b7.configure(foreground="#000000")
        self.b7.configure(highlightbackground="#d9d9d9")
        self.b7.configure(highlightcolor="black")
        self.b7.configure(overrelief="flat")
        self.b7.configure(pady="0")
        self.b7.configure(relief='groove')
        self.b7.configure(text='''Button''')
        self.b7.configure(textvariable=tictactoe_support.b7)

        self.b8 = tk.Button(top)
        self.b8.place(relx=0.65, rely=0.685, height=135, width=180)
        self.b8.configure(activebackground="#d9d9d9")
        self.b8.configure(activeforeground="#000000")
        self.b8.configure(background="#d9d9d9")
        self.b8.configure(disabledforeground="#a3a3a3")
        self.b8.configure(foreground="#000000")
        self.b8.configure(highlightbackground="#d9d9d9")
        self.b8.configure(highlightcolor="black")
        self.b8.configure(pady="0")
        self.b8.configure(relief='groove')
        self.b8.configure(text='''Button''')
        self.b8.configure(textvariable=tictactoe_support.b8)

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.283, rely=0.02, height=71, width=264)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#ffffff")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font10)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(textvariable=tictactoe_support.playerText)

if __name__ == '__main__':
    vp_start_gui()





