#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#    Mar 16, 2019 07:37:14 PM EDT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global b0
    b0 = tk.StringVar()
    b0.set('Button')
    global b3
    b3 = tk.StringVar()
    b3.set('Button')
    global b4
    b4 = tk.StringVar()
    b4.set('Button')
    global b1
    b1 = tk.StringVar()
    b1.set('Button')
    global b2
    b2 = tk.StringVar()
    b2.set('Button')
    global b5
    b5 = tk.StringVar()
    b5.set('Button')
    global b6
    b6 = tk.StringVar()
    b6.set('Button')
    global b7
    b7 = tk.StringVar()
    b7.set('Button')
    global b8
    b8 = tk.StringVar()
    b8.set('Button')
    global playerText
    playerText = tk.StringVar()
    playerText.set('Label')

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import tictactoe
    tictactoe.vp_start_gui()




