#############################################################################
# Generated by PAGE version 4.20
#  in conjunction with Tcl version 8.6
#  Mar 18, 2019 02:13:37 PM EDT  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Segoe UI} -size 18 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font10
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x511+540+159
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1061
    wm minsize $top 176 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Tic Tac Toe"
    vTcl:DefineAlias "$top" "TicTacToeTL" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure Button -background #d9d9d9
    ttk::style configure Button -foreground #000000
    ttk::style configure Button -font TkDefaultFont
    button $top.but43 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -relief groove -text Button -textvariable b0 
    vTcl:DefineAlias "$top.but43" "b0" vTcl:WidgetProc "TicTacToeTL" 1
    button $top.but44 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -relief groove -text Button -textvariable b3 
    vTcl:DefineAlias "$top.but44" "b3" vTcl:WidgetProc "TicTacToeTL" 1
    button $top.but45 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -relief groove -text Button -textvariable b4 
    vTcl:DefineAlias "$top.but45" "b4" vTcl:WidgetProc "TicTacToeTL" 1
    button $top.but46 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -relief groove -text Button -textvariable b1 
    vTcl:DefineAlias "$top.but46" "b1" vTcl:WidgetProc "TicTacToeTL" 1
    button $top.but47 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -relief groove -text Button -textvariable b2 
    vTcl:DefineAlias "$top.but47" "b2" vTcl:WidgetProc "TicTacToeTL" 1
    button $top.but48 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -relief groove -text Button -textvariable b5 
    vTcl:DefineAlias "$top.but48" "b5" vTcl:WidgetProc "TicTacToeTL" 1
    button $top.but49 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -relief groove -text Button -textvariable b6 
    vTcl:DefineAlias "$top.but49" "b6" vTcl:WidgetProc "TicTacToeTL" 1
    button $top.but50 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -overrelief flat \
        -pady 0 -relief groove -text Button -textvariable b7 
    vTcl:DefineAlias "$top.but50" "b7" vTcl:WidgetProc "TicTacToeTL" 1
    button $top.but51 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -relief groove -text Button -textvariable b8 
    vTcl:DefineAlias "$top.but51" "b8" vTcl:WidgetProc "TicTacToeTL" 1
    label $top.lab52 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -textvariable playerText 
    vTcl:DefineAlias "$top.lab52" "Label1" vTcl:WidgetProc "TicTacToeTL" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but43 \
        -in $top -x 0 -relx 0.05 -y 70 -rely 0.044 -width 0 -relwidth 0.3 \
        -height 135 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but44 \
        -in $top -x 30 -y 220 -width 180 -height 135 -anchor nw \
        -bordermode ignore 
    place $top.but45 \
        -in $top -x 210 -y 220 -width 180 -height 135 -anchor nw \
        -bordermode ignore 
    place $top.but46 \
        -in $top -x 210 -y 90 -width 180 -height 135 -anchor nw \
        -bordermode ignore 
    place $top.but47 \
        -in $top -x 390 -y 90 -width 180 -height 135 -anchor nw \
        -bordermode ignore 
    place $top.but48 \
        -in $top -x 390 -y 220 -width 180 -height 135 -anchor nw \
        -bordermode ignore 
    place $top.but49 \
        -in $top -x 30 -y 350 -width 180 -height 135 -anchor nw \
        -bordermode ignore 
    place $top.but50 \
        -in $top -x 210 -y 350 -width 180 -height 135 -anchor nw \
        -bordermode ignore 
    place $top.but51 \
        -in $top -x 390 -y 350 -width 180 -height 135 -anchor nw \
        -bordermode ignore 
    place $top.lab52 \
        -in $top -x 170 -y 10 -width 264 -relwidth 0 -height 71 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

